// @ts-nocheck
import * as __fd_glob_62 from "../content/docs/user/resume-builder/resumes.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/user/resume-builder/resume-templates.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/user/resume-builder/resume-preview.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/user/resume-builder/resume-export.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/user/profiles/skills.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/user/profiles/settings.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/user/profiles/projects.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/user/legal/privacy.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/user/interviews/wpm.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/user/interviews/star.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/user/interviews/scores.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/user/interviews/reports.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/user/interviews/interviews.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/user/interviews/fillers.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/user/interviews/audio.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/user/getting-started/onboarding.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/user/billing/support.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/user/billing/payment-methods.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/user/billing/billing.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/user/billing/billing-plans.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/user/billing/annual-billing.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/dev/overview/quickstart.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/dev/overview/intro.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/dev/overview/deploy.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/dev/integrations/stripe.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/dev/integrations/stripe-webhooks.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/dev/integrations/clerk-webhooks.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/dev/engines/websockets.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/dev/engines/vapi.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/dev/engines/groq.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/dev/engines/gemini.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/dev/engines/elevenlabs.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/dev/engines/ai-engine.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/dev/checker/star-grading.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/dev/checker/ats-rules.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/dev/checker/ats-pdf.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/dev/architecture/sync.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/dev/architecture/middleware.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/dev/architecture/db-schema.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/dev/aesthetics/three-shaders.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/dev/aesthetics/three-bloom.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/dev/aesthetics/lenis.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/dev/aesthetics/gsap-pinning.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/dev/aesthetics/design-system.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/dev/administration/admin.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/user/index.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/dev/index.mdx?collection=docs"
import { default as __fd_glob_15 } from "../content/docs/user/resume-builder/meta.json?collection=docs"
import { default as __fd_glob_14 } from "../content/docs/user/profiles/meta.json?collection=docs"
import { default as __fd_glob_13 } from "../content/docs/user/legal/meta.json?collection=docs"
import { default as __fd_glob_12 } from "../content/docs/user/interviews/meta.json?collection=docs"
import { default as __fd_glob_11 } from "../content/docs/user/getting-started/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../content/docs/user/billing/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/dev/overview/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/dev/integrations/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/dev/engines/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/dev/checker/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/dev/architecture/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/dev/aesthetics/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/dev/administration/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/user/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/dev/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "dev/meta.json": __fd_glob_1, "user/meta.json": __fd_glob_2, "dev/administration/meta.json": __fd_glob_3, "dev/aesthetics/meta.json": __fd_glob_4, "dev/architecture/meta.json": __fd_glob_5, "dev/checker/meta.json": __fd_glob_6, "dev/engines/meta.json": __fd_glob_7, "dev/integrations/meta.json": __fd_glob_8, "dev/overview/meta.json": __fd_glob_9, "user/billing/meta.json": __fd_glob_10, "user/getting-started/meta.json": __fd_glob_11, "user/interviews/meta.json": __fd_glob_12, "user/legal/meta.json": __fd_glob_13, "user/profiles/meta.json": __fd_glob_14, "user/resume-builder/meta.json": __fd_glob_15, }, {"dev/index.mdx": __fd_glob_16, "user/index.mdx": __fd_glob_17, "dev/administration/admin.mdx": __fd_glob_18, "dev/aesthetics/design-system.mdx": __fd_glob_19, "dev/aesthetics/gsap-pinning.mdx": __fd_glob_20, "dev/aesthetics/lenis.mdx": __fd_glob_21, "dev/aesthetics/three-bloom.mdx": __fd_glob_22, "dev/aesthetics/three-shaders.mdx": __fd_glob_23, "dev/architecture/db-schema.mdx": __fd_glob_24, "dev/architecture/middleware.mdx": __fd_glob_25, "dev/architecture/sync.mdx": __fd_glob_26, "dev/checker/ats-pdf.mdx": __fd_glob_27, "dev/checker/ats-rules.mdx": __fd_glob_28, "dev/checker/star-grading.mdx": __fd_glob_29, "dev/engines/ai-engine.mdx": __fd_glob_30, "dev/engines/elevenlabs.mdx": __fd_glob_31, "dev/engines/gemini.mdx": __fd_glob_32, "dev/engines/groq.mdx": __fd_glob_33, "dev/engines/vapi.mdx": __fd_glob_34, "dev/engines/websockets.mdx": __fd_glob_35, "dev/integrations/clerk-webhooks.mdx": __fd_glob_36, "dev/integrations/stripe-webhooks.mdx": __fd_glob_37, "dev/integrations/stripe.mdx": __fd_glob_38, "dev/overview/deploy.mdx": __fd_glob_39, "dev/overview/intro.mdx": __fd_glob_40, "dev/overview/quickstart.mdx": __fd_glob_41, "user/billing/annual-billing.mdx": __fd_glob_42, "user/billing/billing-plans.mdx": __fd_glob_43, "user/billing/billing.mdx": __fd_glob_44, "user/billing/payment-methods.mdx": __fd_glob_45, "user/billing/support.mdx": __fd_glob_46, "user/getting-started/onboarding.mdx": __fd_glob_47, "user/interviews/audio.mdx": __fd_glob_48, "user/interviews/fillers.mdx": __fd_glob_49, "user/interviews/interviews.mdx": __fd_glob_50, "user/interviews/reports.mdx": __fd_glob_51, "user/interviews/scores.mdx": __fd_glob_52, "user/interviews/star.mdx": __fd_glob_53, "user/interviews/wpm.mdx": __fd_glob_54, "user/legal/privacy.mdx": __fd_glob_55, "user/profiles/projects.mdx": __fd_glob_56, "user/profiles/settings.mdx": __fd_glob_57, "user/profiles/skills.mdx": __fd_glob_58, "user/resume-builder/resume-export.mdx": __fd_glob_59, "user/resume-builder/resume-preview.mdx": __fd_glob_60, "user/resume-builder/resume-templates.mdx": __fd_glob_61, "user/resume-builder/resumes.mdx": __fd_glob_62, });