// @ts-nocheck
import { default as __fd_glob_49 } from "../content/docs/user/meta.json?collection=docs"
import { default as __fd_glob_48 } from "../content/docs/dev/meta.json?collection=docs"
import { default as __fd_glob_47 } from "../content/docs/meta.json?collection=docs"
import * as __fd_glob_46 from "../content/docs/user/wpm.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/user/support.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/user/star.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/user/skills.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/user/settings.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/user/scores.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/user/resumes.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/user/resume-templates.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/user/resume-preview.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/user/resume-export.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/user/reports.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/user/projects.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/user/privacy.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/user/payment-methods.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/user/onboarding.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/user/interviews.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/user/index.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/user/fillers.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/user/billing.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/user/billing-plans.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/user/audio.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/user/annual-billing.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/dev/websockets.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/dev/vapi.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/dev/three-shaders.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/dev/three-bloom.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/dev/sync.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/dev/stripe.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/dev/stripe-webhooks.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/dev/star-grading.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/dev/quickstart.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/dev/middleware.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/dev/lenis.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/dev/intro.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/dev/index.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/dev/gsap-pinning.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/dev/groq.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/dev/gemini.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/dev/elevenlabs.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/dev/design-system.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/dev/deploy.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/dev/db-schema.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/dev/clerk-webhooks.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/dev/ats-rules.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/dev/ats-pdf.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/dev/ai-engine.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/dev/admin.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_47, "dev/meta.json": __fd_glob_48, "user/meta.json": __fd_glob_49, }, {"dev/admin.mdx": __fd_glob_0, "dev/ai-engine.mdx": __fd_glob_1, "dev/ats-pdf.mdx": __fd_glob_2, "dev/ats-rules.mdx": __fd_glob_3, "dev/clerk-webhooks.mdx": __fd_glob_4, "dev/db-schema.mdx": __fd_glob_5, "dev/deploy.mdx": __fd_glob_6, "dev/design-system.mdx": __fd_glob_7, "dev/elevenlabs.mdx": __fd_glob_8, "dev/gemini.mdx": __fd_glob_9, "dev/groq.mdx": __fd_glob_10, "dev/gsap-pinning.mdx": __fd_glob_11, "dev/index.mdx": __fd_glob_12, "dev/intro.mdx": __fd_glob_13, "dev/lenis.mdx": __fd_glob_14, "dev/middleware.mdx": __fd_glob_15, "dev/quickstart.mdx": __fd_glob_16, "dev/star-grading.mdx": __fd_glob_17, "dev/stripe-webhooks.mdx": __fd_glob_18, "dev/stripe.mdx": __fd_glob_19, "dev/sync.mdx": __fd_glob_20, "dev/three-bloom.mdx": __fd_glob_21, "dev/three-shaders.mdx": __fd_glob_22, "dev/vapi.mdx": __fd_glob_23, "dev/websockets.mdx": __fd_glob_24, "user/annual-billing.mdx": __fd_glob_25, "user/audio.mdx": __fd_glob_26, "user/billing-plans.mdx": __fd_glob_27, "user/billing.mdx": __fd_glob_28, "user/fillers.mdx": __fd_glob_29, "user/index.mdx": __fd_glob_30, "user/interviews.mdx": __fd_glob_31, "user/onboarding.mdx": __fd_glob_32, "user/payment-methods.mdx": __fd_glob_33, "user/privacy.mdx": __fd_glob_34, "user/projects.mdx": __fd_glob_35, "user/reports.mdx": __fd_glob_36, "user/resume-export.mdx": __fd_glob_37, "user/resume-preview.mdx": __fd_glob_38, "user/resume-templates.mdx": __fd_glob_39, "user/resumes.mdx": __fd_glob_40, "user/scores.mdx": __fd_glob_41, "user/settings.mdx": __fd_glob_42, "user/skills.mdx": __fd_glob_43, "user/star.mdx": __fd_glob_44, "user/support.mdx": __fd_glob_45, "user/wpm.mdx": __fd_glob_46, });